# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechid', models.IntegerField()),
                ('isavail', models.BooleanField(default=False)),
                ('last', models.DateTimeField()),
                ('mlat', models.FloatField(null=True)),
                ('mlon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_text', models.CharField(max_length=100)),
                ('bike_engine', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('reg_type', models.CharField(max_length=50)),
                ('reg_id', models.CharField(max_length=500)),
                ('mlat', models.FloatField(null=True)),
                ('mlon', models.FloatField(null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50, null=True)),
                ('shop', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('home_lat', models.FloatField(null=True)),
                ('home_lon', models.FloatField(null=True)),
                ('job', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('pin', models.IntegerField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trnx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('usrid', models.IntegerField(null=True)),
                ('mechid', models.IntegerField(null=True)),
                ('ack', models.BooleanField(default=False)),
                ('budget', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('pin', models.IntegerField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minor.brand'),
        ),
    ]
