# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trnx',
            name='damagetext',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
