# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0002_auto_20160403_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
