# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0003_auto_20160403_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='password',
            field=models.CharField(default='pass', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanic',
            name='reg_type',
            field=models.CharField(default='reg_type', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanic',
            name='usrname',
            field=models.CharField(default='usrname', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
