# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0004_auto_20160403_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
