# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0005_auto_20160404_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='shop',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
