# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-02 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0006_mechanic_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='trnx',
            name='ack',
            field=models.BooleanField(default=False),
        ),
    ]
